name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest
    name: Update package

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
    
    - name: Use .NET 3.1.405
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build WorldCount.WPF.Styles/WorldCount.WPF.Styles.csproj -c Debug --no-restore
        dotnet build Tests/WorldCount.WPF.Styles.Tests/WorldCount.WPF.Styles.Tests.csproj -c Debug --no-restore
      
    - name: Run Test
      run: dotnet test Tests/WorldCount.WPF.Styles.Tests/WorldCount.WPF.Styles.Tests.csproj --no-build --no-restore --verbosity normal
      
    - name: Packing
      run: dotnet pack WorldCount.WPF.Styles/WorldCount.WPF.Styles.csproj --no-build -c Release -v q
      
    - name: Publish package
      run: dotnet nuget push WorldCount.WPF.Styles/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -n --skip-duplicate -k ${{ secrets.NUGETAPIKEY }}
      
