name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest
    name: Update package

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
    
    - name: Use .NET 3.1.405
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
