name: Publish NuGet.org

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    name: Update package

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use .NET 3.1.405
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
        
    - name: Building
      run: |
        dotnet build WorldCount.WPF.Styles\WorldCount.WPF.Styles.csproj -c Release
        dotnet build Tests\WorldCount.WPF.Styles.Tests\WorldCount.WPF.Styles.Tests.csproj -c Release
        
    - name: Testing
      run: dotnet test Tests\WorldCount.WPF.Styles.Tests\WorldCount.WPF.Styles.Tests.csproj
      
    - name: Packing
      run: dotnet pack WorldCount.WPF.Styles\WorldCount.WPF.Styles.csproj --no-build -c Release -v q
      
      
